version: "2"
services:
  geth:
    image: "ethereum/client-go:stable"
    command:
      - --http
      - --http.api=eth,web3,txpool,net
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/jwtsecret
      - --datadir=/data
      - --syncmode=full
      - --networkid=${CHAIN_ID:-32382}
      - --nat=extip:$EXTERNAL_IP
    ports:
      - $GETH_PORT:8545
    volumes:
      - ./root_signer:/data
      - ./jwtsecret:/jwtsecret
      
  beacon-chain:
#    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:stable"
    image: repo.mind-dev.com/santiops/beacon-chain
    command:
      - --datadir=/data
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=1
      - --minimum-peers-per-subnet=0
      - --genesis-state=/files/genesis.ssz
      - --bootstrap-node=enr:-LG4QOWrpyHnyKr9Ya62t0rpOgygFKPw51g7M4oDEBevvE4vcAdx8pWRl5t7cCO0ve1C6lPDnHmldMBIIbeTM8h0q1CGAYn6NgmEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhMO9YJ2Jc2VjcDI1NmsxoQLyirWTAY--P_8vYX0N0AtINF5p37yEP6N8QI3EoCUBkYN1ZHCCdmY
      - --chain-config-file=/files/config.yml
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --grpc-gateway-corsdomain=*
      - --execution-endpoint=http://geth:8551
      - --accept-terms-of-use
      - --jwt-secret=/jwtsecret
      - --suggested-fee-recipient=$REWARD_RECIPIENT_ADDRESS
      - --verbosity=debug
      - --p2p-host-ip=$EXTERNAL_IP
      - --p2p-tcp-port=$BECONCHAIN_PORT
      - --p2p-udp-port=$BECONCHAIN_PORT
      - --p2p-static-id
    ports:
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/tcp
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/udp
       - 172.17.0.1:$BECONCHAIN_MONITOR_PORT:8080/tcp
    volumes:
      - ./root_beaconchain:/data
      - ./files:/files
      - ./jwtsecret:/jwtsecret
    depends_on:
      geth:
        condition: service_started

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:stable"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/data
      - --accept-terms-of-use
      - --chain-config-file=/files/config.yml
      - --wallet-dir=/files/wallet
      - --wallet-password-file=/files/validator.txt
      - --enable-builder
    volumes:
      - ./root_validator:/data
      - ./files:/files
    depends_on:
      beacon-chain:
        condition: service_started