version: "3.9"
services:
  #Creates a genesis state for the beacon chain using a YAML configuration file and
  # a deterministic set of 64 validators.
  create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl@sha256:f84353a4b6552dbb2cd0f3249d7b02f1a18ccdd56dfb36a233b5814832aa5707"
    command:
      - testnet
      - generate-genesis
      - --fork=bellatrix
      - --deposit-json-file=/files/validator_keys/$DEPOSIT_DATA
      - --num-validators=$NUM_VALIDATORS
      - --output-ssz=/files/genesis.ssz
      - --chain-config-file=/files/config.yml
      - --geth-genesis-json-in=/files/genesis.json
      - --geth-genesis-json-out=/files/genesis.json
    volumes:
      - ./files:/files
