version: "2"
services:
  geth:
    image: "ethereum/client-go:stable"
    command:
      - --http
      - --http.api=eth,web3,txpool,net
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/jwtsecret
      - --datadir=/data
      - --syncmode=full
      - --networkid=${CHAIN_ID:-32382}
      - --nat=extip:$EXTERNAL_IP
    ports:
      - $GETH_PORT:8545
    volumes:
      - ./root_signer:/data
      - ./jwtsecret:/jwtsecret
      
  beacon-chain:
#    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:stable"
    image: repo.mind-dev.com/santiops/beacon-chain
    command:
      - --datadir=/data
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=1
      - --minimum-peers-per-subnet=0
      - --genesis-state=/files/genesis.ssz
      - --bootstrap-node=enr:-LG4QK26GBVo37KwknBeQ8ubca9W4jHtjqeszlRJflvsJeoAXXuUK21U6Q_QTijYrAFbKExFw46mWG1Q344npc39UF-GAYpLbegxh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhKweAAKJc2VjcDI1NmsxoQLyirWTAY--P_8vYX0N0AtINF5p37yEP6N8QI3EoCUBkYN1ZHCCdmY
      - --chain-config-file=/files/config.yml
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --grpc-gateway-corsdomain=*
      - --contract-deployment-block=0
      - --execution-endpoint=http://geth:8551
      - --accept-terms-of-use
      - --jwt-secret=/jwtsecret
      - --suggested-fee-recipient=$WALLET
      - --verbosity=debug
      - --p2p-host-ip=$EXTERNAL_IP
      - --p2p-tcp-port=$BECONCHAIN_PORT
      - --p2p-udp-port=$BECONCHAIN_PORT
      - --p2p-static-id
    ports:
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/tcp
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/udp
       - 172.17.0.1:$BECONCHAIN_MONITOR_PORT:8080/tcp
    volumes:
      - ./root_beaconchain:/data
      - ./files:/files
      - ./jwtsecret:/jwtsecret
    depends_on:
      geth1:
        condition: service_started