version: "2"
services:
  geth:
    image: "ethereum/client-go:stable"
    command:
      - --http
      - --http.api=eth,web3,txpool,net
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/jwtsecret
      - --datadir=/data
      - --syncmode=full
      - --networkid=${CHAIN_ID:-32382}
      - --nat=extip:$EXTERNAL_IP
      - --port=$GETH_P2P_PORT
      - --bootnodes=enode://b20e87044eeb41ce50e7d7929e343dc9319d1fd917caca78b77c3355e898c4501d5a33a6c6d97b5184b8f3930f1d58b51ae2fc989174480a28e7f4abf81f791e@84.32.188.95:0?discport=30310
    ports:
      - $GETH_PORT:8545
      - $GETH_P2P_PORT:$GETH_P2P_PORT
    volumes:
      - ./root_signer:/data
      - ./jwtsecret:/jwtsecret

  beacon-chain:
#    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:stable"
    image: repo.mind-dev.com/sanchain/beacon-chain
    command:
      - --datadir=/data
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=0
      - --minimum-peers-per-subnet=0
      - --genesis-state=/files/genesis.ssz
      - --bootstrap-node=enr:-LG4QJtpFpHQ2ujKfDq7PUW_UdsBGFVWS_reQPHA4TxgFsbEDogWrniH_37tq6FJirddJNS8bkyw50j33_R-OVV_CaqGAYrKbU6Oh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhFQgvF-Jc2VjcDI1NmsxoQLyirWTAY--P_8vYX0N0AtINF5p37yEP6N8QI3EoCUBkYN1ZHCCMtI 
      - --chain-config-file=/files/config.yml
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --grpc-gateway-corsdomain=*
      - --contract-deployment-block=0
      - --execution-endpoint=http://geth:8551
      - --accept-terms-of-use
      - --jwt-secret=/jwtsecret
      - --suggested-fee-recipient=$REWARD_RECIPIENT_ADDRESS
      - --disable-peer-scorer
      - --p2p-host-ip=$EXTERNAL_IP
      - --p2p-tcp-port=$BECONCHAIN_PORT
      - --p2p-udp-port=$BECONCHAIN_PORT
      - --p2p-static-id
      - --disable-peer-scorer
      - --slasher
      - --historical-slasher-node
      - --slasher-datadir=/data
    ports:
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/tcp
       - $BECONCHAIN_PORT:$BECONCHAIN_PORT/udp
       - $BECONCHAIN_MONITOR_PORT:8080/tcp
       - 172.17.0.1:3500:3500/tcp
    volumes:
      - ./root_beaconchain:/data
      - ./files:/files
      - ./jwtsecret:/jwtsecret
    depends_on:
      geth:
        condition: service_started

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:stable"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/data
      - --accept-terms-of-use
      - --chain-config-file=/files/config.yml
      - --wallet-dir=/files/wallet
      - --wallet-password-file=/files/validator.txt
      - --enable-builder
      - --monitoring-host=0.0.0.0
    ports:
       - $VALIDATOR_MONITOR_PORT:8081/tcp
    volumes:
      - ./root_validator:/data
      - ./files:/files
    depends_on:
      beacon-chain:
        condition: service_started