CONFIG_NAME: sanchain-pos-dev
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089
# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090
# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0
# Capella
CAPELLA_FORK_EPOCH: 2
CAPELLA_FORK_VERSION: 0x20000092

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242


# Time parameters
# mainnet 12
SECONDS_PER_SLOT: 5 # SecondsPerSlot is how many seconds are in a single slot.
# mainnet 2**5 (= 32) slots 6.4 minutes
SLOTS_PER_EPOCH: 16 # SlotsPerEpoch is the number of slots in an epoch.
# mainnet 14
SECONDS_PER_ETH1_BLOCK: 6 # SecondsPerETH1Block is the approximate time for a single eth1 block to be produced.

# Deposit balance
# mainnet 2**5 * 10**9 (= 32,000,000,000) Gwei
MAX_EFFECTIVE_BALANCE: 2048000000000 # MaxEffectiveBalance is the maximal amount of Gwei that is effective for staking.
# mainnet 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 1024000000000 # EjectionBalance is the minimal GWei a validator needs to have before ejected.
# mainnet 2**0 * 10**9 (= 1,000,000,000) Gwei
EFFECTIVE_BALANCE_INCREMENT: 64000000000 # EffectiveBalanceIncrement is used for converting the high balance into the low balance for validators.

# Deposit time
# mainnet 2**6 (= 64) epochs ~6.8 hours
# min 4
EPOCHS_PER_ETH1_VOTING_PERIOD: 32 # EpochsPerEth1VotingPeriod defines how often the merkle root of deposit receipts get updated in beacon node on per epoch basis.
# mainnet 2**11 (= 2,048) Eth1 blocks ~8 hours
# min 16
ETH1_FOLLOW_DISTANCE: 512 # Eth1FollowDistance is the number of eth1.0 blocks to wait before considering a new deposit for voting. This only applies after the chain as been started.
